InseeFr/Bauhaus-Back-Office

src/main/java/fr/insee/rmes/persistance/service/sesame/operations/families/FamiliesQueries.java, src/main/java/fr/insee/rmes/persistance/service/sesame/operations/families/FamiliesUtils.java, src/main/java/fr/insee/rmes/persistance/service/sesame/operations/series/SeriesUtils.java, src/main/resources/request/operations/families/checkIfFamilyExistsQuery.flth
=> Add link between a new series and its family

src/main/resources/xslTransformerFiles/sims2fodt.xsl
Duplicate RICH_TEXT data in OS export... No duplicate in local : try to correct with a patch in XSLT...
=> Dec export OS bis

src/main/java/fr/insee/rmes/bauhaus_services/OperationsService.java, src/main/java/fr/insee/rmes/bauhaus_services/code_list/CodeListServiceImpl.java, src/main/java/fr/insee/rmes/bauhaus_services/operations/OperationsImpl.java, src/main/java/fr/insee/rmes/bauhaus_services/rdf_utils/RdfUtils.java, src/main/java/fr/insee/rmes/bauhaus_services/structures/utils/StructureComponentUtils.java, src/main/java/fr/insee/rmes/model/structures/MutualizedComponent.java, src/main/java/fr/insee/rmes/persistance/sparql_queries/operations/indicators/IndicatorsQueries.java, src/main/java/fr/insee/rmes/webservice/operations/IndicatorsResources.java, src/main/resources/request/codes-list/getDetailedCodesList.ftlh, src/main/resources/request/structures/getMutualizedComponent.ftlh, src/main/resources/request/structures/getStructure.ftlh
=> feat: add contraints to Components.

pom.xml, src/main/java/fr/insee/rmes/bauhaus_services/classifications/ClassificationPublication.java, src/main/java/fr/insee/rmes/bauhaus_services/code_list/CodeListPublication.java, src/main/java/fr/insee/rmes/bauhaus_services/concepts/collections/CollectionsUtils.java, src/main/java/fr/insee/rmes/bauhaus_services/concepts/concepts/ConceptsUtils.java, src/main/java/fr/insee/rmes/bauhaus_services/concepts/publication/ConceptsPublication.java, src/main/java/fr/insee/rmes/bauhaus_services/keycloak/KeycloakServices.java, src/main/java/fr/insee/rmes/bauhaus_services/keycloak/Token.java, src/main/java/fr/insee/rmes/bauhaus_services/keycloak/token.java, src/main/java/fr/insee/rmes/bauhaus_services/operations/documentations/DocumentationPublication.java, src/main/java/fr/insee/rmes/bauhaus_services/operations/documentations/DocumentationsUtils.java, src/main/java/fr/insee/rmes/bauhaus_services/operations/documentations/documents/DocumentsPublication.java, src/main/java/fr/insee/rmes/bauhaus_services/operations/families/FamilyPublication.java, src/main/java/fr/insee/rmes/bauhaus_services/operations/indicators/IndicatorPublication.java, src/main/java/fr/insee/rmes/bauhaus_services/operations/operations/OperationPublication.java, src/main/java/fr/insee/rmes/bauhaus_services/operations/series/SeriesPublication.java, src/main/java/fr/insee/rmes/bauhaus_services/rdf_utils/RdfService.java, src/main/java/fr/insee/rmes/bauhaus_services/rdf_utils/RepositoryGestion.java, src/main/java/fr/insee/rmes/bauhaus_services/rdf_utils/RepositoryPublication.java, src/main/java/fr/insee/rmes/bauhaus_services/rdf_utils/RepositoryUtils.java, src/main/java/fr/insee/rmes/bauhaus_services/structures/utils/ComponentPublication.java, src/main/java/fr/insee/rmes/bauhaus_services/structures/utils/StructurePublication.java, src/main/java/fr/insee/rmes/bauhaus_services/structures/utils/StructureUtils.java, src/main/java/fr/insee/rmes/config/Config.java, src/main/java/fr/insee/rmes/webservice/HealthcheckApi.java, src/main/java/fr/insee/rmes/webservice/LoaderResources.java
=> Fusion des commits OIDC dans main

src/main/java/fr/insee/rmes/webservice/HealthcheckApi.java, src/main/resources/bauhaus-dev.properties, src/test/java/fr/insee/rmes/stubs/RepositoryGestionStub.java, src/test/java/fr/insee/rmes/stubs/RepositoryPublicationStub.java, src/test/java/fr/insee/rmes/stubs/RepositoryPublicationStubInternalError.java, src/test/java/fr/insee/rmes/webservice/HealthcheckApiTest.java
check of all repos fail if the first ones fail
=> fix healthcheck pbs and test it

pom.xml
=> feat: update Spring Boot Parent POM

src/main/java/fr/insee/rmes/bauhaus_services/operations/families/FamiliesUtils.java, src/main/java/fr/insee/rmes/bauhaus_services/rdf_utils/RdfUtils.java, src/main/java/fr/insee/rmes/model/operations/Family.java, src/main/resources/request/operations/famOpeSer/getFamily.ftlh, src/test/java/fr/insee/rmes/bauhaus_services/operations/families/FamiliesUtilsTest.java
=> feat: review abstract value for family

src/main/java/fr/insee/rmes/bauhaus_services/operations/OperationsImpl.java, src/main/java/fr/insee/rmes/bauhaus_services/operations/indicators/IndicatorsUtils.java, src/main/java/fr/insee/rmes/bauhaus_services/rdf_utils/RdfUtils.java, src/main/java/fr/insee/rmes/persistance/sparql_queries/operations/indicators/IndicatorsQueries.java, src/main/java/fr/insee/rmes/webservice/operations/IndicatorsResources.java, src/main/resources/request/operations/indicators/getIndicator.ftlh, src/test/java/fr/insee/rmes/bauhaus_services/operations/indicators/IndicatorsUtilsTest.java
=> feat: review abstract and history uri for indicator #352

src/main/java/fr/insee/rmes/bauhaus_services/operations/OperationsImpl.java, src/main/java/fr/insee/rmes/bauhaus_services/operations/series/SeriesUtils.java, src/main/java/fr/insee/rmes/bauhaus_services/rdf_utils/RdfUtils.java, src/main/java/fr/insee/rmes/bauhaus_services/rdf_utils/RepositoryGestion.java, src/main/java/fr/insee/rmes/persistance/sparql_queries/operations/series/OpSeriesQueries.java, src/main/java/fr/insee/rmes/webservice/operations/SeriesResources.java, src/main/resources/request/operations/series/getSeriesById.ftlh, src/test/java/fr/insee/rmes/bauhaus_services/operations/series/SeriesUtilsTest.java
=> feat: review series history and abstract predicates

src/main/resources/bauhaus-dev.properties, src/main/resources/xslTransformerFiles/concept/conceptPatternContent.xml
=>  fix: solve issue parent/child relationship with concept when exporting

src/main/java/fr/insee/rmes/bauhaus_services/concepts/ConceptsCollectionServiceImpl.java, src/main/java/fr/insee/rmes/bauhaus_services/concepts/ConceptsImpl.java, src/main/java/fr/insee/rmes/bauhaus_services/concepts/collections/ConceptUtils.java, src/main/java/fr/insee/rmes/bauhaus_services/rdf_utils/RdfService.java, src/main/java/fr/insee/rmes/config/Config.java, src/main/java/fr/insee/rmes/model/concepts/CollectionForExport.java, src/main/java/fr/insee/rmes/utils/ExportUtils.java, src/main/java/fr/insee/rmes/utils/FilesUtils.java, src/main/resources/bauhaus-core.properties, src/main/resources/bauhaus-dev.properties, src/test/java/fr/insee/rmes/stubs/ConfigStub.java, src/test/java/fr/insee/rmes/utils/FileUtilsTest.java
=> feat: shorten long file name when exporting

.github/workflows/ci.yml
=> feat: init github action

src/main/java/fr/insee/rmes/bauhaus_services/concepts/concepts/ConceptsUtils.java, src/main/java/fr/insee/rmes/utils/ExportUtils.java, src/main/java/fr/insee/rmes/webservice/operations/MetadataReportResources.java, src/main/resources/request/operations/documentations/documents/getDocumentsUriAndUrlForSims.ftlh
=> feat: add header when missing document when downloading sims

src/main/java/fr/insee/rmes/bauhaus_services/rdf_utils/RdfUtils.java, src/main/resources/request/operations/famOpeSer/getFamily.ftlh, src/main/resources/request/operations/indicators/getIndicator.ftlh, src/main/resources/request/operations/series/getSeriesById.ftlh
=> feat: review Operation History and Abstract triplets

src/main/java/fr/insee/rmes/config/Config.java, src/main/java/fr/insee/rmes/config/auth/security/DefaultSecurityContext.java, src/main/java/fr/insee/rmes/config/auth/security/OpenIDConnectSecurityContext.java, src/main/resources/bauhaus-core.properties, src/test/java/fr/insee/rmes/config/auth/security/OpenIDConnectSecurityContextTest.java
=> Utiliser un timbre anonyme lorsque l'utilisateur n'en a pas

src/main/java/fr/insee/rmes/bauhaus_services/GeographyService.java, src/main/java/fr/insee/rmes/bauhaus_services/geography/GeographyServiceImpl.java, src/main/resources/request/geography/getGeoFeatures.ftlh
=> feat: add lg2 to territory label

pom.xml, src/main/java/fr/insee/rmes/bauhaus_services/rdf_utils/RepositoryPublication.java, src/main/java/fr/insee/rmes/bauhaus_services/rdf_utils/RepositoryUtils.java
internal publication bug : use bad property for  the rdf server url
=> Fix internal publication 

src/main/java/fr/insee/rmes/bauhaus_services/operations/documentations/documents/DocumentsImpl.java, src/main/java/fr/insee/rmes/bauhaus_services/operations/documentations/documents/DocumentsUtils.java, src/main/java/fr/insee/rmes/webservice/operations/DocumentsResources.java, src/test/java/fr/insee/rmes/bauhaus_services/keycloak/KeycloakServicesTest.java, src/test/java/fr/insee/rmes/webservice/DocumentsResourcesTest.java
* feat: improve error message when downloading a missing document
* feat: update tes
=> feat: improve error message when downloading a missing document (#403)

src/main/java/fr/insee/rmes/bauhaus_services/CodeListService.java, src/main/java/fr/insee/rmes/bauhaus_services/code_list/CodeListPublication.java, src/main/java/fr/insee/rmes/bauhaus_services/code_list/CodeListServiceImpl.java, src/main/java/fr/insee/rmes/config/Config.java, src/main/java/fr/insee/rmes/persistance/sparql_queries/code_list/CodeListQueries.java, src/main/java/fr/insee/rmes/webservice/CodeListsResources.java, src/main/java/fr/insee/rmes/webservice/codelist/CodeListsResources.java, src/main/java/fr/insee/rmes/webservice/codelist/PartialCodeListsResources.java, src/main/resources/bauhaus-core.properties, src/main/resources/request/codes-list/countNumberOfCodes.ftlh, src/main/resources/request/codes-list/getAllCodesLists.ftlh, src/main/resources/request/codes-list/getDetailedCodes.ftlh, src/main/resources/request/codes-list/getDetailedCodesList.ftlh, src/test/java/fr/insee/rmes/bauhaus_services/code_list/CodeListServiceImplTest.java, src/test/java/fr/insee/rmes/persistance/sparql_queries/code_list/CodeListQueriesTest.java, src/test/java/fr/insee/rmes/webservice/CodeListsResourcesTest.java, src/test/java/fr/insee/rmes/webservice/codelist/CodeListsResourcesTest.java, src/test/java/fr/insee/rmes/webservice/codelist/PartialCodeListsResourcesTest.java
=> feat: start the migration of the codes list

src/main/java/fr/insee/rmes/bauhaus_services/operations/documentations/DocumentationsRubricsUtils.java, src/main/java/fr/insee/rmes/webservice/operations/MetadataReportResources.java, src/main/resources/request/operations/documentations/getDocumentationRubricsQuery.ftlh
Reverts InseeFr/Bauhaus-Back-Office#364
=> Revert "feat: review new uri for rich text of a SIMS"

src/main/java/fr/insee/rmes/bauhaus_services/structures/utils/StructureUtils.java, src/test/java/fr/insee/rmes/bauhaus_services/structures/utils/StructureUtilsTest.java
replace this PR : https://github.com/InseeFr/Bauhaus-Back-Office/pull/606
to be rebased with main
=> 605bis delete published structure

src/main/resources/request/getAllGraphs.ftlh, src/test/java/fr/insee/rmes/bauhaus_services/rdf_utils/FreeMarkerUtilsTest.java
problem of trailing space and EOL
=> Fix one test

src/main/java/fr/insee/rmes/bauhaus_services/datasets/DatasetServiceImpl.java, src/main/java/fr/insee/rmes/bauhaus_services/distribution/DistributionService.java, src/main/java/fr/insee/rmes/bauhaus_services/distribution/DistributionServiceImpl.java, src/main/java/fr/insee/rmes/bauhaus_services/rdf_utils/RepositoryGestion.java, src/main/java/fr/insee/rmes/exceptions/ErrorCodes.java, src/main/java/fr/insee/rmes/model/dataset/Distribution.java, src/main/java/fr/insee/rmes/webservice/distribution/DistributionResources.java, src/main/resources/bauhaus-core.properties, src/main/resources/request/distribution/getDistribution.ftlh, src/test/java/fr/insee/rmes/bauhaus_services/distribution/DistributionServiceImplTest.java, src/test/java/fr/insee/rmes/integration/authorizations/TestDistributionsResourcesEnvProd.java
=> 495 : etre capable de supprimer une distribution

src/main/java/fr/insee/rmes/webservice/codesLists/CodeListsResources.java
endpoint 
POST /codeList 
instead of 
POST /codeList/
=> fix: no slash at the end for POST /codeList

.github/workflows/quality.yml
=> fix (quality action syntax error)

src/main/java/fr/insee/rmes/bauhaus_services/StampAuthorizationChecker.java, src/main/java/fr/insee/rmes/bauhaus_services/code_list/CodeListServiceImpl.java, src/main/java/fr/insee/rmes/bauhaus_services/operations/documentations/documents/DocumentsImpl.java, src/main/java/fr/insee/rmes/bauhaus_services/operations/documentations/documents/DocumentsUtils.java, src/main/java/fr/insee/rmes/exceptions/RmesExceptionHandler.java, src/main/java/fr/insee/rmes/persistance/ontologies/INSEE.java, src/main/java/fr/insee/rmes/persistance/sparql_queries/code_list/CodeListQueries.java, src/main/java/fr/insee/rmes/persistance/sparql_queries/operations/documentations/DocumentsQueries.java, src/main/java/fr/insee/rmes/webservice/codesLists/CodeListsResources.java, src/main/resources/request/codes-list/getCodeListIRIByNotation.ftlh, src/main/resources/request/codes-list/getDetailedCodesList.ftlh, src/main/resources/request/operations/documentations/documents/changeDocumentUrlQuery.ftlh, src/test/java/fr/insee/rmes/bauhaus_services/datasets/DistributionServiceImplStubContainer.java
- Rename Code List Predicate
- Fix issue when updating document
=> fix: change codelist predicate

src/main/java/fr/insee/rmes/config/auth/security/CommonSecurityConfiguration.java, src/main/resources/bauhaus-local-dev.properties, src/test/java/fr/insee/rmes/integration/CorsConfigDefaultToAppHostPropertyForOriginTest.java, src/test/java/fr/insee/rmes/integration/CorsConfigTest.java
=> Fix cors config

src/main/resources/application.properties
Add property `spring.servlet.multipart.enabled=true`
=> fix : add MultipartFile property

pom.xml
=> pom: update dependencies

src/test/java/fr/insee/rmes/bauhaus_services/classifications/ClassificationsImplTest.java, src/test/java/fr/insee/rmes/bauhaus_services/classifications/item/ClassificationItemServiceImplTest.java, src/test/java/fr/insee/rmes/bauhaus_services/concepts/collections/CollectionsUtilsTest.java, src/test/java/fr/insee/rmes/bauhaus_services/concepts/concepts/ConceptsUtilsTest.java, src/test/java/fr/insee/rmes/bauhaus_services/keycloak/TokenTest.java, src/test/java/fr/insee/rmes/bauhaus_services/operations/ParentUtilsTest.java, src/test/java/fr/insee/rmes/bauhaus_services/operations/documentations/MetadataStructureDefUtilsTest.java, src/test/java/fr/insee/rmes/bauhaus_services/operations/documentations/documents/DocumentsImplTest.java, src/test/java/fr/insee/rmes/bauhaus_services/operations/documentations/documents/DocumentsUtilsTest.java, src/test/java/fr/insee/rmes/integration/authorizations/ConceptsAuthorizationsTest.java, src/test/java/fr/insee/rmes/webservice/CodeListsResourcesTest.java, src/test/java/fr/insee/rmes/webservice/classifications/ClassificationsResourcesTest.java, src/test/java/fr/insee/rmes/webservice/concepts/ConceptsResourcesTest.java, src/test/java/fr/insee/rmes/webservice/datasets/DatasetResourcesTest.java, src/test/java/fr/insee/rmes/webservice/datasets/DistributionResourcesTest.java, src/test/java/fr/insee/rmes/webservice/operations/DocumentsResourcesTest.java
=> feature : improve methods for CodeListsResourcesTest.java

src/test/java/fr/insee/rmes/bauhaus_services/code_list/CodeListItemTest.java, src/test/java/fr/insee/rmes/bauhaus_services/code_list/DetailedCodeListTest.java, src/test/java/fr/insee/rmes/bauhaus_services/operations/OperationsImplTest.java, src/test/java/fr/insee/rmes/bauhaus_services/operations/documentations/MetadataStructureDefUtilsTest.java, src/test/java/fr/insee/rmes/bauhaus_services/organizations/OrganizationUtilsTest.java, src/test/java/fr/insee/rmes/bauhaus_services/organizations/OrganizationsServiceImplTest.java, src/test/java/fr/insee/rmes/model/ValidationStatusTest.java, src/test/java/fr/insee/rmes/model/structures/ComponentDefinitionTest.java, src/test/java/fr/insee/rmes/model/structures/MutualizedComponentTest.java, src/test/java/fr/insee/rmes/model/structures/StructureTest.java, src/test/java/fr/insee/rmes/rbac/UnknownApplicationExceptionTest.java, src/test/java/fr/insee/rmes/rbac/UnknownPrivilegeExceptionTest.java, src/test/java/fr/insee/rmes/rbac/UnknownRoleExceptionTest.java, src/test/java/fr/insee/rmes/rbac/stamps/DefaultStampCheckerTest.java, src/test/java/fr/insee/rmes/webservice/PublicResourcesTest.java
=> Augmenter la couverture de tests de Bauhaus-Back-office

src/test/java/fr/insee/rmes/bauhaus_services/ConstantsTest.java, src/test/java/fr/insee/rmes/bauhaus_services/operations/OperationsImplTest.java, src/test/java/fr/insee/rmes/config/ConfigStubTest.java, src/test/java/fr/insee/rmes/config/ConfigTest.java, src/test/java/fr/insee/rmes/config/auth/roles/RolesTest.java, src/test/java/fr/insee/rmes/config/swagger/model/IdLabelTwoLangsTest.java, src/test/java/fr/insee/rmes/exceptions/errors/CodesListErrorCodesTest.java
=> 948 augmenter la couverture de tests bauhaus back office

src/test/java/fr/insee/rmes/config/ConfigTest.java, src/test/java/fr/insee/rmes/config/PropertiesKeysTest.java, src/test/java/fr/insee/rmes/config/swagger/model/AcceptTest.java, src/test/java/fr/insee/rmes/config/swagger/model/IdLabelAltLabelSimsTest.java, src/test/java/fr/insee/rmes/config/swagger/model/IdLabelAltLabelTest.java, src/test/java/fr/insee/rmes/config/swagger/model/IdLabelTest.java, src/test/java/fr/insee/rmes/config/swagger/model/LabelUrlTest.java, src/test/java/fr/insee/rmes/config/swagger/model/code_list/CodeLabelListTest.java, src/test/java/fr/insee/rmes/config/swagger/model/code_list/CodeLabelTwoLangsTest.java, src/test/java/fr/insee/rmes/config/swagger/model/code_list/CodeListTest.java, src/test/java/fr/insee/rmes/config/swagger/model/code_list/PageTest.java, src/test/java/fr/insee/rmes/config/swagger/model/concepts/CollectionByIdTest.java, src/test/java/fr/insee/rmes/config/swagger/model/concepts/CollectionMembersTest.java, src/test/java/fr/insee/rmes/config/swagger/model/concepts/CollectionsDashboardTest.java, src/test/java/fr/insee/rmes/config/swagger/model/concepts/CollectionsToValidateTest.java, src/test/java/fr/insee/rmes/config/swagger/model/concepts/ConceptByIdTest.java, src/test/java/fr/insee/rmes/config/swagger/model/concepts/ConceptLinksTest.java, src/test/java/fr/insee/rmes/config/swagger/model/concepts/ConceptNotesTest.java, src/test/java/fr/insee/rmes/config/swagger/model/concepts/ConceptsSearchTest.java, src/test/java/fr/insee/rmes/config/swagger/model/concepts/ConceptsToValidateTest.java, src/test/java/fr/insee/rmes/config/swagger/model/operations/documentation/AttributeTest.java, src/test/java/fr/insee/rmes/config/swagger/model/operations/documentation/DocumentIdTest.java, src/test/java/fr/insee/rmes/config/swagger/model/organizations/OrganizationTest.java, src/test/java/fr/insee/rmes/config/swagger/model/structure/IdLabelTypeTest.java, src/test/java/fr/insee/rmes/config/swagger/model/structure/StructureByIdTest.java
=> refactor: improve code coverage

src/test/java/fr/insee/rmes/config/swagger/model/application/InitTest.java, src/test/java/fr/insee/rmes/config/swagger/model/application/PersonsTest.java
=> feat:  add tests for Bauhaus-Back-Office

src/test/java/fr/insee/rmes/bauhaus_services/code_list/export/ExportedCodeTest.java, src/test/java/fr/insee/rmes/bauhaus_services/code_list/export/ExportedCodesListTest.java, src/test/java/fr/insee/rmes/config/auth/user/AuthorizeMethodDeciderTest.java, src/test/java/fr/insee/rmes/config/auth/user/FakeUserConfigurationTest.java, src/test/java/fr/insee/rmes/config/auth/user/PreAuthorizeCheckerTest.java, src/test/java/fr/insee/rmes/config/auth/user/StampTest.java, src/test/java/fr/insee/rmes/config/auth/user/UserTest.java, src/test/java/fr/insee/rmes/config/freemarker/FreemarkerConfigTest.java, src/test/java/fr/insee/rmes/config/keycloak/KeycloakServerZoneConfigurationTest.java, src/test/java/fr/insee/rmes/external/services/authentication/stamps/RmesStampsImplTest.java
=> feat: method for RmesStampsImplTest.java
